### PR TITLE
Check for invalid uses of .form-control

### LINKED ISSUE #262: Using .form-control on the wrong kind of form control should be an error
Valid controls: Textual `<input>`s, `<textarea>`s, `<select>`s
X-Ref: https://github.com/twbs/bootstrap/issues/16123

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #262.
CC: @hnrch02 for review

### CODE REVIEW

File: src/bootlint.js [hunk 1]
```diff
@@ -905,6 +905,35 @@ var LocationIndex = _location.LocationIndex;
             reporter('`.carousel-inner` must have exactly one `.item.active` child.', innersWithWrongActiveItems);
         }
     });
+    addLinter("E042", function lintFormControlOnWrongControl($, reporter) {
+        var formControlsOnWrongTags = $('.form-control:not(input):not(textarea):not(select)');
```
Comment (hnrch02) [inline src/bootlint.js]: Wouldn't `$('.form-control:not(input, textarea, select)')` also work?

**Comment by hnrch02** [comment]
Otherwise LGTM.

File: src/bootlint.js (hunk 1 above)
Comment (cvrebert) [inline src/bootlint.js]: Oh yeah, I always forget that that works. Let me change it then.
(There are a few other lint checks that unnecessarily use multiple `:not`s too, fyi)
